name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ansible-vault-cli-github-action:latest
    - name: Create encrypted file
      run: bash tests/tests.sh
    - uses: actions/ansible-vault-cli-github-action@latest
      with:
        vault_key: '1234'
        command: "echo 'fake confidential data' > foo.yml && ansible-vault encrypt foo.yml && cat foo.yml"