name: Docker Image CI

on:
  push:
    branches: [ tests ]
  pull_request:
    branches: [ tests ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ansible-vault-cli-github-action:latest
    - name: Create encrypted file
      run: bash tests/tests.sh
